name: Generar Video para YouTube

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Tema del video"
        required: true
        default: "la depresión"

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
    - name: Chequear el repositorio
      uses: actions/checkout@v3

    - name: Configurar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        python3 -m pip install --upgrade pip
        pip install requests gtts moviepy

    - name: Generar el video
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
      run: |
        python3 scripts/create_video.py "${{ github.event.inputs.topic }}"

    - name: Subir el video como artefacto
      uses: actions/upload-artifact@v3
      with:
        name: video-final
        path: output/video.mp4
