name: Generar Video para YouTube

on:
  workflow_dispatch:

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
    - name: Chequear el repositorio
      uses: actions/checkout@v3

    - name: Configurar dependencias
      run: |
        sudo apt-get update && sudo apt-get install -y ffmpeg
        python3 -m pip install --upgrade pip
        pip install requests gtts moviepy

    - name: Generar el video
      run: |
        python3 scripts/create_video.py "la depresión"

    - name: Subir artefactos
      uses: actions/upload-artifact@v3
      with:
        name: video-final
        path: output/video.mp4
