name: Generate Automated Video

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-generativeai edge-tts Pillow requests
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Create directories
        run: |
          test -d images || mkdir images
          test -d output || mkdir output

      - name: Check fallback images
        run: |
          ls -l images/fallback*.jpg

      - name: Generate content
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python scripts/generate_content.py

      - name: Debug files
        run: |
          ls -l images
          ls -l output
          cat subtitles.srt

      - name: Generate video
        run: bash scripts/generate_video.sh

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: generated-video
          path: output/final_video.mp4
