name: Generate Automated Video

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Ejecuta diariamente a medianoche
  workflow_dispatch: # Permite ejecución manual

jobs:
  generate-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-generativeai edge-tts Pillow requests
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Verify images folder
        run: |
          ls -l images/ || echo "Carpeta images/ no encontrada, creándola"
          mkdir -p images
          ls -l images/

      - name: Generate video content and images
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python scripts/generate_content.py

      - name: Debug: List generated files
        run: |
          echo "Contenido de images/"
          ls -l images/
          echo "Contenido de output/"
          ls -l output/ || echo "Carpeta output/ no existe"
          echo "Contenido de subtitles.srt"
          cat subtitles.srt || echo "subtitles.srt no existe"

      - name: Generate video
        run: bash scripts/generate_video.sh

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-video
          path: output/final_video.mp4
